### ISSUE TITLE
Spec in Markdown

### ISSUE THREAD

**Issue by sjackman** [pmelsted/GFA-spec#1]
Would you be okay with writing the spec in Markdown rather than LaTeX? I much prefer writing in Markdown than LaTeX. I think we're at the point where more people are comfortable with Markdown than LaTeX, so it's more inclusive to the community. GitHub renders Markdown pretty. It's easy to convert Markdown to LaTeX using pandoc. I'm okay if the answer is no, but I thought I'd ask.

**Comment by pmelsted** [comment]
Sounds good, I'll add you to the repo and you can switch to pandoc.

**Comment by sjackman** [comment]
Done.
