### ISSUE TITLE
Regex Notation

### ISSUE THREAD

**Issue by noporpoise** [pmelsted/GFA-spec#10]
The Segment line 'Name' regex in `GFA-spec.md` doesn't make sense. I hope I'm reading it correctly. 

`[!-)+-<>-~][!-~]*` matches "!~" but not "1", "2" etc. which are used in the example at the bottom of the document. 

I think the author meant something like `[^-)+-<>-~][^-~]*`, where `^` at the beginning of a set is used to mean the negation of the set ie. may not start with the special characters given, may not contain either `-` or `~`.

This is the regex syntax used by grep and perl. More info here: http://www.regular-expressions.info/charclass.html

**Comment by noporpoise** [comment]
Just had a thought that it might be clearer to specify a Segment Name regex of: `[a-zA-Z0-9_.]+` and clarify that names are case-sensitive.

**Comment by noporpoise** [comment]
I had a second look at the regex with an ASCII table to hand. It turns out that `!-)` is the range of characters from `!` to `)` and so the whole regex is equivalent to: `[^\n\t *=][^\n\t ]*`. The original regex is actually more specific in that it prohibits unprintable control characters. However it is very hard to read - it is not immediately obvious that the only printable characters prohibited are whitespace characters and the name cannot start with '*' or '='. 

I'll close this issue and open a pull request to add an explanation of the regex. Apologies for the misunderstanding.

**Comment by sjackman** [comment]
These regex could be made more readable by using character classes. See http://www.regular-expressions.info/posixbrackets.html
Something like `[^[:cntrl:]*=][:graph:]*`
I haven't checked that this regex is exactly equivalent.
