### ISSUE TITLE
Copy text verbatim from Heng Li's blog posts

### ISSUE THREAD

**Issue by sjackman** [pmelsted/GFA-spec#2]
The text can be edited after a bulk import. I'd like to import the unedited text so that the edits are retained in the git history.

+ http://lh3.github.io/2014/07/19/a-proposal-of-the-grapical-fragment-assembly-format/
+ http://lh3.github.io/2014/07/23/first-update-on-gfa/

**Comment by pmelsted** [comment]
into the markdown itself, I guess that's fine

**Comment by sjackman** [comment]
@lh3 Could you send us a copy of the original source code for these blog posts? Does it happen to be in Markdown?

**Comment by lh3** [comment]
See here:

https://github.com/lh3/lh3.github.com/tree/master/_posts

**Comment by sjackman** [comment]
Of course. I should have figured that out for myself. Thanks, Heng.
