### ISSUE TITLE
No version in the spec

### ISSUE THREAD

**Issue by lmrodriguezr** [pmelsted/GFA-spec#27]
The current version of the spec is not explicitly stated. I think it should be added in a visible place for both parser and generator developers.

**Comment by sjackman** [comment]
Good point. ABySS is using `1.0`, which is what Heng used in his original proposal:
http://lh3.github.io/2014/07/19/a-proposal-of-the-grapical-fragment-assembly-format/
https://github.com/bcgsc/abyss/blob/master/Graph/GfaIO.h#L24

In retrospect, I would have preferred a prerelease version like `0.1`, but it doesn't much matter really.

**Comment by lmrodriguezr** [comment]
The current specs only have one name per segment, but the same document includes examples with two names per segment (for the 5' and 3' ends) and an additional 5th column `*` (CIGAR?). These examples don't conform with the current specification, but they both have a `VN:Z:1.0` header. Is any available software using the name-per-end style? Abyss is using the name-per-sequence style, and that's also what [Shaun's examples][1] use.

How would you feel if the version of the name-per-end style was retroactively downgraded to something like `VN:Z:0.1`? I know it's not great practice, but having two conflicting versions with the same version number is even more confusing. Bumping the current version up wouldn't really solve the problem, since Abyss and others are already using the current spec with `VN:Z:1.0`.

Perhaps the name-per-end examples (and discussion) could actually be moved to a *discussion* or *historic background* document on it's own, so the spec doc is cleaner for developers implementing parsers/generators.

[1]: https://github.com/sjackman/assembly-graph/blob/master/sample.gfa

**Comment by sjackman** [comment]
> but the same document includes examples with two names per segment (for the 5' and 3' ends) and an additional 5th column * (CIGAR?)

Where are these? Do you mean Heng's doc? The "name-per-end" is purely historical. It is confusing that his doc and our doc both use `1.0`, but I don't see a simple solution. I say we just stick our fingers in our ears and ignore it.

**Comment by pmelsted** [comment]
Yes, in Heng's original version both the forward and reverse complement were specified. This has since been abandoned and those examples no longer match the spec.

**Comment by sjackman** [comment]
I forgot that we have Heng's two docs included verbatim in our spec.
https://github.com/pmelsted/GFA-spec/blob/master/GFA-spec.md#a-proposal-of-the-grapical-fragment-assembly-format
https://github.com/pmelsted/GFA-spec/blob/master/GFA-spec.md#first-update-on-gfa
Yes, these should be removed, and any relevant content incorporated into our spec.

**Comment by sjackman** [comment]
The current version of the spec is 1.0 `H VN:Z:1.0`.
