### ISSUE TITLE
Wrong regexp for segment sequence

### ISSUE THREAD

**Issue by lmrodriguezr** [pmelsted/GFA-spec#28]
The regexp of col 3 for segment line appears to be broader than intended. It currently reads `\*|[A-Za-z=.]+`, but I think the dot is unescaped by mistake, it should be `\*|[A-Za-z=\.]+`.

**Comment by sjackman** [comment]
The dot `.` inside the square brackets does not need to be escaped.
Try `grep '[.]' <<<hi`

**Comment by lmrodriguezr** [comment]
How many times have I unnecessarily escaped dots inside square brackets!!!

**Comment by sjackman** [comment]
There's always something new to learn in the world of *nix!
